name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem does this feature address?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
  - type: textarea
    id: context
    attributes:
      label: Additional context

